name: qsr_app
description: A new Flutter project for QSR ordering.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.4.0 # For making API calls to backend
  provider: ^6.0.0 # For managing the app's state
  flutter_animate: ^4.5.0 # For GSAP-like animations
  flutter_staggered_animations: ^1.1.1 # For staggered list animations
  visibility_detector: ^0.4.0+2 # For scroll-triggered animations
  animations: ^2.0.11 # For page transitions

  # Backend Integration (Firebase temporarily disabled for web compatibility)
  # firebase_core: ^2.24.2 # Firebase core functionality
  # firebase_auth: ^4.15.3 # Firebase authentication (temporarily disabled)
  # cloud_firestore: ^4.13.6 # Firestore database (temporarily disabled)
  # firebase_analytics: ^10.7.4 # Analytics tracking (temporarily disabled)
  # firebase_messaging: ^14.7.10 # Push notifications (temporarily disabled)

  # Payment Processing (Stripe temporarily disabled for testing)
  # flutter_stripe: ^9.5.0 # Stripe payments

  # Additional utilities
  shared_preferences: ^2.2.2 # Local storage
  connectivity_plus: ^5.0.2 # Network connectivity
  dio: ^5.4.0 # Advanced HTTP client
  web_socket_channel: ^2.4.0 # WebSocket support for real-time notifications

  # Offline storage
  hive: ^2.2.3 # NoSQL local database
  hive_flutter: ^1.1.0 # Hive Flutter integration
  sqflite: ^2.3.0 # SQLite local database
  path: ^1.8.3 # Path utilities

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/CC-Penta-3.png

  fonts:
    - family: SofiaRoughBlackThree
      fonts:
        - asset: assets/fonts/SofiaRoughBlackThree.ttf
          weight: 900
    
    - family: MontserratBlack
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
    
    - family: SofiaSans
      fonts:
        - asset: assets/fonts/SofiaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/SofiaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/SofiaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SofiaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/SofiaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SofiaSans-Black.ttf
          weight: 900
