name: qsr_app
description: A new Flutter project for QSR ordering.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.4.0 # For making API calls to Revel Systems
  provider: ^6.0.0 # For managing the app's state
  flutter_animate: ^4.5.0 # For GSAP-like animations
  flutter_staggered_animations: ^1.1.1 # For staggered list animations
  visibility_detector: ^0.4.0+2 # For scroll-triggered animations
  animations: ^2.0.11 # For page transitions

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/CC-Penta-3.png

  fonts:
    - family: SofiaRoughBlackThree
      fonts:
        - asset: assets/fonts/SofiaRoughBlackThree.ttf
          weight: 900
    
    - family: MontserratBlack
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
    
    - family: SofiaSans
      fonts:
        - asset: assets/fonts/SofiaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/SofiaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/SofiaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SofiaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/SofiaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SofiaSans-Black.ttf
          weight: 900
